### ISSUE TITLE
Multiple Launchpads in sync

### ISSUE THREAD

**Issue by sourceoftruthdata** [obeezzy/lpminimk3#111]
First off, this is an incredible utility for customizing Launchpads.  Thanks so much!!  

Like the request mentions, I'm very interesting in extending this work beyond a single Launchpad (and actually managed to hack together 2 independent LP's), but I'm curious is there a recommended way of increasing the # of lp's?  in addition, can they sync together as a single display.  Thanks again!

**Comment by obeezzy** [comment]
@sourceoftruthdata, thanks for your interest! Right now I have only tried connecting one Launchpad to my computer. `lpminimk3.find_launchpads()` should return all the Launchpads connected to your computer as a list. However, I haven't tested that yet so results may vary.

To answer your second question, there is no official support for syncing displays at the moment. I'm currently working on getting a couple features in that should at least make implementing syncing easy. I will update the documentation accordingly once I'm done.

**Comment by obeezzy** [comment]
@sourceoftruthdata, so I've made a couple updates within the last couple days. Long story short, try these commands when you get the chance:
1. First, pull the latest version of this repo on two computers. They must be connected to the same local network and pingable.
2. Start the sync server (the `-a` option makes the server listen for all hosts):
```bash
$ PYTHONPATH=. python -m lpminimk3.graphics.sync -a
```
3. On the remote computer, run the sync client with the Launchpad connected:
```bash
$ PYTHONPATH=. python -m lpminimk3.examples.sync_client -i <ip-address-or-hostname-of-other-computer>
```
4. Visit the [LP Sketch](https://www.lpsketch.com) website.
5. Ensure that the indicator on the top left corner of the page is green and says `Connected` next to it.
6. Press a button on the Launchpad picture on the webpage. You should see the physical Launchpad (connected to the remote computer) light up.

Let me know if you run into any issues.
