### ISSUE TITLE
find_launchpads() method broken in Windows 10

### ISSUE THREAD

**Issue by matthewwachter** [obeezzy/lpminimk3#95]
There seems to be an issue with the SystemMidiPortParser class for windows.

This is what MidiOut and MidiIn return on my system:

`['Microsoft GS Wavetable Synth 0', 'LPMiniMK3 MIDI 1', 'MIDIOUT2 (LPMiniMK3 MIDI) 2']
['LPMiniMK3 MIDI 0', 'MIDIIN2 (LPMiniMK3 MIDI) 1']`

So the find_launchpads() method doesn't find it because the prefixes do not include the windows version and if I add them to the list of prefixes it has an issue parsing it. (e.g 'LPMiniMK3 MIDI')

I think the way you have it set it up it's expecting a ":" in the port name which doesn't appear to be there in windows (or at least on my machine).

**Comment by yatesdr** [comment]
This issue cropped up for me in MacOS 13.3.1 using python 3.9.

Same issue, solved by commenting out these same lines in utils.py.
